# Book settings
title: Data Science Handbook
author: Dennis Zheng
#logo: logo.png


only_build_toc_files: true

execute:
  execute_notebooks: cache

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url : https://github.com/dennissxz/data-science-handbook
  branch : master

html:
  use_repository_button: true
  use_issues_button: true

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
