# Book settings
title: Data Science Handbook
author: Dennis Zheng
#logo: logo.png


only_build_toc_files: true

execute:
  execute_notebooks: cache

latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url : https://github.com/dennissxz/data-science-handbook
  branch : master

html:
  use_repository_button: true
  use_issues_button: true
  google_analytics_id: UA-150740237-2

launch_buttons:
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-svg.js
    # tex-mml-chtml
    html_js_files:
        - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
parse:
    myst_extended_syntax: true
    # myst_enable_extensions:
      # - dollarmath
      # - linkify
      # - deflist
      # - replacements
